// flow-typed signature: a6f2bfc55316c2aa49408448d5fb54bf
// flow-typed version: <<STUB>>/i18next-parser_v^0.12.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-parser/bin/cli' {
  declare module.exports: any;
}

declare module 'i18next-parser/src/helpers' {
  declare module.exports: any;
}

declare module 'i18next-parser/test/helpers' {
  declare module.exports: any;
}

declare module 'i18next-parser/test/parser' {
  declare module.exports: any;
}

declare module 'i18next-parser/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-parser/bin/cli.js' {
  declare module.exports: $Exports<'i18next-parser/bin/cli'>;
}
declare module 'i18next-parser/index' {
  declare module.exports: $Exports<'i18next-parser'>;
}
declare module 'i18next-parser/index.js' {
  declare module.exports: $Exports<'i18next-parser'>;
}
declare module 'i18next-parser/src/helpers.js' {
  declare module.exports: $Exports<'i18next-parser/src/helpers'>;
}
declare module 'i18next-parser/test/helpers.js' {
  declare module.exports: $Exports<'i18next-parser/test/helpers'>;
}
declare module 'i18next-parser/test/parser.js' {
  declare module.exports: $Exports<'i18next-parser/test/parser'>;
}
declare module 'i18next-parser/test/test.js' {
  declare module.exports: $Exports<'i18next-parser/test/test'>;
}
