// flow-typed signature: a05a6c6948b59b8f34f6b4102002658f
// flow-typed version: <<STUB>>/lodash.flattendeep_v^4.4.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.flattendeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.flattendeep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.flattendeep/index' {
  declare module.exports: $Exports<'lodash.flattendeep'>;
}
declare module 'lodash.flattendeep/index.js' {
  declare module.exports: $Exports<'lodash.flattendeep'>;
}
