export const apiCallIds = {
  LOGIN: 'LOGIN',
  CONFIRM_LOGIN: 'CONFIRM_LOGIN',
  SIGN_UP: 'SIGN_UP',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  FORGOTTEN_PASSWORD: 'FORGOTTEN_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESEND_EMAIL_VERIFICATION: 'RESEND_EMAIL_VERIFICATION',
};
