name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
          cache: 'yarn'
      - run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn format-check
          yarn test
          yarn build
        env:
          CI: true
