name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: |
          npm ci
          npm run lint
          npm run format-check
          npm run test
          npm run build
        env:
          CI: true
